### ISSUE TITLE
Bug - PrettyGCode Not able to be reordered

### ISSUE THREAD

**Issue by DylanCDuke** [Kragrathea/OctoPrint-PrettyGCode#41]
Doesn't look like I can reorder using Tab Order, or Dragon Order. Both keep it on the last position

**Comment by sr1329** [comment]
Same issues here.

**Comment by Kragrathea** [comment]
Hmm. Hey @jneilliii do you have any idea why Dragon Order doesn't work with this plugin? Maybe I have to do something to the tab first?

**Comment by jneilliii** [comment]
This might actually be a bug on my side. Recent changes to OctoPrint converted the default GCode viewer into a plugin, and I'm doing a replace on the word gcode with gcodeviewer and it's causing your plugin's ID to get renamed and not match up correctly. It's getting saved as `plugin_prettygcodeviewer` instead of what it should be `plugin_prettygcode`. Let me see if I can fix that real quick for you guys by making the replace more restrictive.

**Comment by jneilliii** [comment]
Just release version 0.1.6 of Dragon Order that should fix this.

**Comment by jneilliii** [comment]
Just released version 0.5.11 of Tab Order that should fix this.

**Comment by Kragrathea** [comment]
Thanks! I am going to close this then.

**Comment by DylanCDuke** [comment]
Thanks guys! I'll update when my current print is done and let you know if if this is resolved on my end!
