### ISSUE TITLE
Feature Request: Different color for current layer

### ISSUE THREAD

**Issue by mneumark** [Kragrathea/OctoPrint-PrettyGCode#49]
In the normal GCode viewer you can limit it to just the current layer and such.

In 3d like it is in PrettyGCode, its hard to tell where we are in the current layer, it would be cool to show 1 color for printed stuff, 1 color for stuff to be printed on the current layer, and stuff already printed on the current layer. Make all of it optional so people can choose what to show, kinda like in the normal GCode viewer.

**Comment by Kragrathea** [comment]
Believe it or not that turns out to be really hard. Mostly because of the tricks I am having to do to make it run fast enough. I basically have to generate all the geometry at load time and that locks in the colors. Only way to change the color is to regenerate the geometry and that is slow and memory intensive.

**Comment by mneumark** [comment]
What if you were to put a thin partially transparent rectangle down on the top, and then print on top of that layer, and then move up that sheet when a layer finishes?
